---
title: "R Notebook"
out: html_notebook
---

```{r Load libraries, message=FALSE, warning=FALSE, include=FALSE}
library(readr)
library(tidyverse)
library(skimr)
library(lubridate)
library(janitor)
library(ggrepel)
library(zoo)
library(directlabels)
library(grid)
library(epiDisplay) # tab1 function for cumulative sum
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load data
```{r}
load("~/Desktop/prospectus/data/ripa/ripa.RData")
```

# stops
```{r}
# Number of stops
n_stops <- ripa %>% group_by(rfs, yearmonth, year, race, gender) %>%
	count()  
colnames(n_stops) <-  c("rfs", "yearmonth", "year", "race", "gender", "n_stops") 
```



# searches and hits
```{r}
# searches and hits person
search_per <- ripa %>% filter(search_person == 1)%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count()
colnames(search_per) <- c("rfs", "yearmonth", "year", "race", "gender", "n_search_per") 

hit_per <- ripa %>% filter(hit_person == 1)%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count() 
colnames(hit_per)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_hit_per") 

sh_per <- merge(search_per, hit_per, all = T)

sh_per[is.na(sh_per)] <- 0

#rowSums(is.na(sh_per))
```

```{r}
n_search_pro <- ripa %>% filter(search_property == 1)%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count() 
colnames(n_search_pro)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_search_pro") 


n_hit_pro <- ripa %>% filter(hit_property == 1)%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count() 
colnames(n_hit_pro)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_hit_pro") 

sh_pro <- merge(n_search_pro, n_hit_pro, all = T)

sh_pro[is.na(sh_pro)] <- 0

```



```{r}
sh <- merge(sh_per, sh_pro, all = T)

```



```{r}
stops_sh <- merge(n_stops, sh, all = T)
stops_sh[is.na(stops_sh)] <- 0
```




```{r}
# Arrest
 arrest <- ripa %>% filter(ros1_arrest == 1) %>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count()  

colnames(arrest)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_arrest") 


citation <-  ripa %>% filter(ros2_citation ==1)%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count()  
colnames(citation)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_citation") 


interview <-  ripa %>% filter(ros3_interview ==1)%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count()  
colnames(interview)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_interview") 


naw <-  ripa %>% filter(ros4_naw == 1 )%>%
  group_by(rfs, yearmonth, year, race, gender) %>%
	count() 

colnames(naw)  <-  c("rfs", "yearmonth", "year", "race", "gender", "n_naw") 


```



```{r}
ros1 <- merge(arrest, citation, all = T )
ros1[is.na(ros1)] <- 0

ros2 <- merge(interview, naw, all = T )
ros2[is.na(ros2)] <- 0

ros <- merge(ros1, ros2, all = T)


ros[is.na(ros)] <- 0

```



```{r}
stops_sh_ros <- merge(stops_sh, ros, all = T)
```

```{r}
monthly <- stops_sh_ros

```




```{r}
monthly <- monthly %>% mutate(
  population  = case_when(
    race == "Asian" &  gender == "Male" ~ 3822238 * (0.117) * .95,
    race == "Asian" &  gender == "Female" ~ 3822238 * (0.117) * .05,
    race == "Black" & gender == "Male" ~ 3822238 * (.086) * .95,
    race == "Black" & gender == "Female" ~ 3822238 * (.086) * .05,
    race == "Hispanic" & gender == "Male" ~ 3822238 * (.484) * .95,
    race == "Hispanic" & gender == "Female" ~ 3822238 * (.484) * .05,
    race == "White" & gender == "Male" ~ 3822238 * (.281) * .95,
    race == "White" & gender == "Female" ~ 3822238 * (.281) * .05))
```





```{r}
monthly <- monthly[, c(1:5, 15, 6:14)]
```





```{r}
monthly <- monthly %>% mutate(r_stops2 = (n_stops/population) * 100, 
                   r_search_per2 = n_search_per/population * 100, # searches person /population
                   r_search_pro2 = n_search_pro/population * 100, # searches property /population
                   r_hit_per1 = n_hit_per/n_search_per, # hit_per
                   r_hit_pro1 = n_hit_pro/n_search_pro, # 
                   r_hit_per2 = n_hit_per/population * 100 , # hit_per
                   r_hit_pro2 = n_hit_pro/population * 100, # 
                   r_arrest1 = n_arrest/n_stops, 
                   r_arrest2 = n_arrest/population * 100,
                   r_citation1 = n_citation/n_stops, 
                   r_citation2 = n_citation/population * 100,
                   r_interview1 = n_interview/n_stops, 
                   r_interview2 = n_interview/population * 100,
                   r_naw1 = n_naw/n_stops,
                   r_naw2 = n_naw/population * 100)
                     
                  
```



```{r}
duration <- ripa %>% group_by(rfs, yearmonth, year, race, gender) %>%
	summarize(avg_duration = mean(duration))  

monthly <- merge(monthly, duration, all = T)

monthly <- monthly %>% mutate(so3 = if_else(yearmonth < "Mar 2022", 0, 1))

```

```{r}
glimpse(monthly)
```

```{r}
save(monthly, file = "~/Desktop/prospectus/data/ripa/monthly.RData")

write.csv(monthly, file = "~/Desktop/prospectus/data/ripa/monthly.csv")
```





